### ISSUE TITLE
[actsys-1317] [Logical Groups] Group Add functionality does not work when using config file as a normal user

### ISSUE THREAD

**Issue by kwangintel** [intel-ctrlsys/actsys#28]
<b><i>[created="Wed, 14 Jun 2017 14:04:43 -0700", resolved="Fri, 16 Jun 2017 14:42:48 -0700"]</i></b>
<p>When using config file as a normal user, the user will not be able to add the groups and throws the python traceback.</p>

<p>How to reproduce:<br/>
1. Use ctrl_db config file to add group <br/>
2. Be a normal user</p>

<p>Execute below command:<br/>
$ctrl datastore group add <node_regex> <group_name></p>

<p>Expected Output:<br/>
Error message, notifying user that you cannot add group as you do not have enough permission.</p>

<p>Actual Output:<br/>
<span class="error">&#91;Errno 13&#93;</span> Permission denied: '/usr/share/ctrl_db'<br/>
Traceback (most recent call last):<br/>
  File "/usr/bin/ctrl", line 14, in <module><br/>
    return_value = ControlCommandLineInterface().execute_cli_cmd()<br/>
  File "/usr/lib/python2.7/site-packages/control/cli/control_cli.py", line 349, in execute_cli_cmd<br/>
    return self.execute_cmd(cmd_args, masterparser, unknown_args)<br/>
  File "/usr/lib/python2.7/site-packages/control/cli/control_cli.py", line 309, in execute_cmd<br/>
    return execute_cmd_internal()<br/>
  File "/usr/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 69, in new_function<br/>
    return function(*args, **kwargs)<br/>
  File "/usr/lib/python2.7/site-packages/control/cli/control_cli.py", line 290, in execute_cmd_internal<br/>
    parse_and_run(unknown_args)<br/>
  File "/usr/lib/python2.7/site-packages/datastore/datastore_cli.py", line 169, in parse_and_run<br/>
    self.retval = args.func(args)<br/>
  File "/usr/lib/python2.7/site-packages/datastore/datastore_cli.py", line 460, in group_execute<br/>
    result = self.datastore.add_to_group(device_list, group)<br/>
  File "/usr/lib/python2.7/site-packages/datastore/filestore.py", line 432, in add_to_group<br/>
    self.save_file()<br/>
  File "/usr/lib/python2.7/site-packages/datastore/filestore.py", line 109, in save_file<br/>
    JsonParser.write_file(location, self.parsed_file)<br/>
  File "/usr/lib/python2.7/site-packages/datastore/utilities.py", line 150, in write_file<br/>
    raise FileNotFound(file_path)<br/>
datastore.utilities.FileNotFound: 'File /usr/share/ctrl_db not found.'</p>

**Comment by kwangintel** [comment]
<b><i>[author="rppendya", created="Fri, 16 Jun 2017 14:42:43 -0700"]</i></b>
<p><a href="https://sid-gerrit.devtools.intel.com/#/c/23095/" class="external-link" rel="nofollow">https://sid-gerrit.devtools.intel.com/#/c/23095/</a></p>

**Comment by kwangintel** [comment]
<b><i>[created="Wed, 21 Jun 2017 09:51:54 -0700"]</i></b>
<p>Issue has been fixed. Now normal user gets proper error message when trying to modify the config file as a normal user.</p>
