### ISSUE TITLE
[actsys-984] Datastore: Python traceback when trying to set device with numeric values

### ISSUE THREAD

**Issue by kwangintel** [intel-ctrlsys/actsys#44]
<b><i>[created="Sun, 12 Mar 2017 17:46:32 -0700", resolved="Thu, 16 Mar 2017 10:53:11 -0700"]</i></b>
<p>Datastore set device function has two arguments. 1) hostname 2) device_type</p>

<p>If you try to use numbers with those arguments like shown below, it provides python traceback instead of providing success/error</p>

<p>How to reproduce: Two methods to reproduce<br/>
1. $python -m datastore device set hostname=1 device_type=node<br/>
OR<br/>
2. $python -m datastore device set hostname=knl device_type=1</p>

<p>Expected Output:<br/>
Either Error or Success Message based on requirements. I will let developer decide what needs to happen</p>

<p>Actual Output:<br/>
Traceback (most recent call last):<br/>
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main<br/>
    "_<em>main</em>_", fname, loader, pkg_name)<br/>
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code<br/>
    exec code in run_globals<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 29, in <module><br/>
    main()<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 25, in main<br/>
    return_value = DataStoreCLI(datastore).parse_and_run()<br/>
  File "datastore/datastore_cli.py", line 103, in parse_and_run<br/>
    self.retval = args.func(args)<br/>
  File "datastore/datastore_cli.py", line 151, in device_execute<br/>
    self.ds.device_upsert(existing_device)<br/>
  File "datastore/postgresstore.py", line 96, in device_upsert<br/>
    self.cursor.callproc("public.upsert_device", args)<br/>
psycopg2.ProgrammingError: function public.upsert_device(unknown, unknown, integer, unknown, unknown, unknown, unknown, unknown) does not exist<br/>
LINE 1: SELECT * FROM public.upsert_device(NULL,'node',1,NULL,NULL,N...<br/>
      ^<br/>
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.</p>

**Comment by kwangintel** [comment]
<b><i>[created="Tue, 21 Mar 2017 14:22:53 -0700"]</i></b>
<p>Issue has been fixed and verified.</p>
