### ISSUE TITLE
[actsys-982] Datastore: Python traceback when trying to set/add the device with profile when profile does not exist.

### ISSUE THREAD

**Issue by kwangintel** [intel-ctrlsys/actsys#46]
<b><i>[created="Sun, 12 Mar 2017 17:18:48 -0700", resolved="Mon, 20 Mar 2017 11:29:23 -0700"]</i></b>
<p>Datastore CLI provides the python traceback when trying to set the device with profile when profile does not exist.</p>

<p>How to reproduce:<br/>
$python -m datastore device set hostname=knl device_type=node profile_name=<fake_name></p>

<p>Expected Output:<br/>
Some error message since the profile_name does not exist in the database.</p>

<p>Actual OutpTraceback (most recent call last):<br/>
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main<br/>
    "_<em>main</em>_", fname, loader, pkg_name)<br/>
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code<br/>
    exec code in run_globals<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 29, in <module><br/>
    main()<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 25, in main<br/>
    return_value = DataStoreCLI(datastore).parse_and_run()<br/>
  File "datastore/datastore_cli.py", line 103, in parse_and_run<br/>
    self.retval = args.func(args)<br/>
  File "datastore/datastore_cli.py", line 151, in device_execute<br/>
    self.ds.device_upsert(existing_device)<br/>
  File "datastore/postgresstore.py", line 96, in device_upsert<br/>
    self.cursor.callproc("public.upsert_device", args)<br/>
psycopg2.IntegrityError: insert or update on table "device" violates foreign key constraint "device_profile"<br/>
DETAIL:  Key (profile_name)=(node) is not present in table "profile".<br/>
CONTEXT:  SQL statement "INSERT INTO public.device(device_type, properties, hostname, ip_address, mac_address, profile_name)<br/>
VALUES(p_device_type, p_properties, p_hostname, p_ip_address, p_mac_address, p_profile_name)<br/>
RETURNING public.device.device_id"<br/>
PL/pgSQL function upsert_device(integer,character varying,character varying,character varying,character varying,character varying,character varying,jsonb) line 5 at SQL statement<br/>
ut:</p>

**Comment by kwangintel** [comment]
<b><i>[created="Tue, 21 Mar 2017 14:26:10 -0700"]</i></b>
<p>Proper error message provided to user when trying to set the device with non existing profile.</p>

<p>Issue has been fixed and verified.</p>
