### ISSUE TITLE
[actsys-976] Datastore: Python traceback when trying to add device without providing device_type

### ISSUE THREAD

**Issue by kwangintel** [intel-ctrlsys/actsys#51]
<b><i>[created="Fri, 10 Mar 2017 15:16:01 -0800", resolved="Thu, 16 Mar 2017 10:51:09 -0700"]</i></b>
<p>When trying to add the device with datastore cli shown below, it provides python traceback instead of providing error:</p>

<p>How to reproduce:<br/>
$python -m datastore device set hostname=knl</p>

<p>Expected output:<br/>
Error message notifying end user about missing device_type</p>

<p>Actual output:<br/>
Traceback (most recent call last):<br/>
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main<br/>
    "_<em>main</em>_", fname, loader, pkg_name)<br/>
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code<br/>
    exec code in run_globals<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 29, in <module><br/>
    main()<br/>
  File "/home/fsp/control-repos/datastore/datastore/_<em>main</em>_.py", line 25, in main<br/>
    return_value = DataStoreCLI(datastore).parse_and_run()<br/>
  File "datastore/datastore_cli.py", line 103, in parse_and_run<br/>
    self.retval = args.func(args)<br/>
  File "datastore/datastore_cli.py", line 151, in device_execute<br/>
    self.ds.device_upsert(existing_device)<br/>
  File "datastore/postgresstore.py", line 93, in device_upsert<br/>
    super(PostgresStore, self).device_upsert(device_info)<br/>
  File "datastore/datastore.py", line 95, in device_upsert<br/>
    raise DataStoreException("device_type is a required key/value in the device_info field")<br/>
datastore.datastore.DataStoreException: 'device_type is a required key/value in the device_info field'</p>

**Comment by kwangintel** [comment]
<b><i>[created="Tue, 21 Mar 2017 14:31:53 -0700"]</i></b>
<p>Issue is fixed and verified.</p>
